### ISSUE TITLE
does this work on Python 3?  I can't seem to make anything work

### ISSUE THREAD

**Issue by ccrome** [mfnch/pyrtist#1]
Hi there,
  I see you have a python3 branch.  But I can't seem to get anything to start.  When I try running setup.py, it complains about no Feature module.  When I remove that, it installs, but doesn't run.  I get an error of no 'gi' module.  I try install pygobject, but I get errors with that too.

Have you had any luck?

Thanks,
 -caleb

**Comment by mfnch** [comment]
Hi,

Thanks for reporting the issue.
The python3-gi branch works for me on Python3 with PyGObject, but I guess I am using an older version of setuptools. I can see that setuptools.Feature was deprecated with a note that it may be removed in future versions, so I guess this is what happened. See https://github.com/pypa/setuptools/issues/58

What error do you get? I suspect it may be due to missing dependencies. I should maybe have a check for all dependencies and report missing modules at startup.

Also note that you should be able to run the program without installing it. From the top repo directory just do "python -m pyrtist" and it should start.

Cheers,
Matteo

**Comment by rboulkhi** [comment]
Hello,

As a matter of fact, the project seems stuck in python2.
I get the error `ModuleNotFoundError: No module named 'pygtk'`, a package which has been replaced by 'pygi' for python 3 versions.
Is this project still alive? Or has it died out because of being out of touch.
I need to know if I could use it for a project I'm working on.

Thanks,
Rachid

**Comment by mfnch** [comment]
This should be fixed in [f5fafc1](https://github.com/mfnch/pyrtist/commit/f5fafc1d3bc53e4115cdc83de65ef2c15eb6ccd0).

rboulkhi, the master branch now only work with python3 and gi.

Feel free to reopen this ticket if you find issues around this.
